CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -I./lib
LDFLAGS = 
LDLIBS = -lreadline -lncurses -lm

SRC = test_tree_234.c
LIB_SRC = lib/lib_tree_234.c lib/lib_key_array.c
LIB_OBJS = $(LIB_SRC:.c=.o)
LIB_STATIC = test_tree_234.a

TARGET = test_tree_234

all: $(TARGET)

$(TARGET): $(SRC) $(LIB_STATIC)
	$(CC) $(CFLAGS) $(LDFLAGS) $(SRC) $(LIB_STATIC) -o $@ $(LDLIBS)

$(LIB_STATIC): $(LIB_OBJS)
	ar rcs $@ $^

lib/%.o: lib/%.c
	$(CC) $(CFLAGS) -c $< -o $@

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f lib/*.o $(TARGET) $(LIB_STATIC)

build_debug:
	$(MAKE) clean
	$(MAKE) CFLAGS="-Wall -Wextra -std=c11 -g -O0 -I./lib"

valgrind: build_debug
	valgrind --leak-check=full --error-exitcode=1 ./$(TARGET)