# Тестовый Makefile

CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -I./lib
LDFLAGS = 
LDLIBS = -lreadline -lncurses -lm

SRC = test_library.c
LIB_SRC = lib/library.c lib/work_library.c lib/dialogue.c
LIB_OBJS = $(LIB_SRC:.c=.o)
LIB_STATIC = libmylib.a

TEST_BIN = test_library

# Сборка тестов
all: $(TEST_BIN)

$(TEST_BIN): $(SRC) $(LIB_STATIC)
	$(CC) $(CFLAGS) $(LDFLAGS) $(SRC) $(LIB_STATIC) -o $@ $(LDLIBS)

$(LIB_STATIC): $(LIB_OBJS)
	ar rcs $@ $^

lib/%.o: lib/%.c
	$(CC) $(CFLAGS) -c $< -o $@

run: $(TEST_BIN)
	./$(TEST_BIN)

clean:
	rm -f lib/*.o $(TEST_BIN) $(LIB_STATIC)

build_debug:
	$(MAKE) clean
	$(MAKE) CFLAGS="-Wall -Wextra -std=c11 -g -O0 -I./lib"

valgrind: build_debug
	valgrind --leak-check=full --error-exitcode=1 ./$(TEST_BIN)
