# Тестовый Makefile

CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -I./lib
LDLIBS = -lm

SRC = test_table.c
LIB_OBJS = lib/library.o lib/work_library.o lib/dialogue.o
LIB_STATIC = libmylib.a

TEST_BIN = test_table

# Сборка тестов
all: $(TEST_BIN)

$(TEST_BIN): $(SRC) $(LIB_STATIC)
	$(CC) $(CFLAGS) $(SRC) $(LIB_STATIC) -o $(TEST_BIN) $(LDLIBS)

$(LIB_STATIC): $(LIB_OBJS)
	ar rcs $@ $^

lib/%.o: lib/%.c
	$(CC) $(CFLAGS) -c $< -o $@

run: $(TEST_BIN)
	./$(TEST_BIN)

clean:
	rm -f lib/*.o $(TEST_BIN) $(LIB_STATIC)
