name: Build and Test Table Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: 🛠 Install build tools
      run: sudo apt update && sudo apt install -y build-essential && sudo apt install -y libreadline-dev

    - name: 🔧 Build and run tests
      run: |
        make -f Makefile.test
        make -f Makefile.test run
