name: Build and Test Table Library

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: 🛠 Install build tools
      run: sudo apt update && sudo apt install -y build-essential libreadline-dev valgrind

    - name: 🔧 Build and run tests
      run: |
        make -f Makefile
        make -f Makefile.test_tree
        make -f Makefile.test_tree build_debug
        make -f Makefile.test_tree valgrind
